### ISSUE TITLE
dbdeployer deploy hangs or takes endlessly on Linux

### ISSUE THREAD

**Issue by geertjanvdk** [datacharmer/dbdeployer#97] opened 2019-10-22 11:58 UTC
**Describe the bug**

Using 1.40.0 we were trying to deploy a single 8.0.18 sandbox. The process was simply hanging, nothing happening, no output. In process list, process was also idle. The issue manifested itself on Ubuntu 18.04.3, but not on macOS. Skipping the library check, however, deployed fine.

**To Reproduce**

Steps to reproduce the behavior on Ubuntu 18.04.3 LTS:

1. dbdeployer deploy single 8.0.18
2. (wait)
3. (wait)
4. Give up after few minutes and Ctrl+C

**Expected behavior**

```
$ dbdeployer deploy single 8.0.18
Database installed in $HOME/sandboxes/msb_8_0_18
run 'dbdeployer usage single' for basic instructions'
. sandbox server started
```

**Environment:**
 - OS: Ubuntu 18.04.3 LTS
 - dbdeployer 1.40.0
 - tarball full name (e.g. mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz)
 - tarball origin (dev.mysql.com - Generic)
 - Go installed from golang.org (1.12.12).
 - Used dbdeployer using `go get` (master) and the released binary.

**Additional context**

We believe the issue to be with the Library Check. On Ubuntu 18.04.3, using `--skip-library-check`, deployment worked. On macOS (where library check is not used), it also works fine without the `--skip-library-check` option.

Note that Ubuntu was still installed with MariaDB, but after removal (purged everything), that also had no effect.

**Comment by datacharmer** [comment] 2019-10-22 12:32
Thanks for reporting an issue.

Unfortunately, I can't reproduce this problem.

```
gmax@gmnuc0:~$ dbdeployer --version
dbdeployer version 1.40.0

gmax@gmnuc0:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

gmax@gmnuc0:~$ dbdeployer unpack ~/downloads/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz
Unpacking tarball /home/gmax/downloads/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz to $HOME/opt/mysql/8.0.18
.........100.........200......263
Renaming directory /home/gmax/opt/mysql/mysql-8.0.18-linux-glibc2.12-x86_64 to /home/gmax/opt/mysql/8.0.18

gmax@gmnuc0:~$ dbdeployer deploy single 8.0.18
Database installed in $HOME/sandboxes/msb_8_0_18
run 'dbdeployer usage single' for basic instructions'
.. sandbox server started

gmax@gmnuc0:~$ ~/sandboxes/msb_8_0_18/test_sb
ok - version '8.0.18'
ok - port detected: 8018
ok - version is 8.0.18 as expected
ok - port is 8018 as expected
ok - query was successful for user msandbox_ro: 'select 1'
ok - query was successful for user msandbox_rw: 'select 1'
ok - query was successful for user msandbox_ro: 'use mysql; select count(*) from information_schema.tables where table_schema=schema()'
ok - query was successful for user msandbox_rw: 'use mysql; select count(*) from information_schema.tables where table_schema=schema()'
ok - query failed as expected for user msandbox_ro: 'create table if not exists test.txyz(i int)'
ok - query was successful for user msandbox_rw: 'create table if not exists test.txyz(i int)'
ok - query was successful for user msandbox_rw: 'drop table if exists test.txyz'
# Tests :    11
# PASS  :    11
# fail  :     0
```

Please try the same command using this docker container running (ubuntu:8.04.3)
```
docker run -ti -v $HOME/opt:/root/opt  -v ~/go/bin/dbdeployer:/usr/bin/dbdeployer datacharmer/my-ubuntu bash
```

If that fails, please try again with the binaries coming from dbdeployer site. I have tried compiling with both Go 1.12 and 1.13, without seeing any difference.

**Comment by datacharmer** [comment] 2019-10-22 12:38
Thinking of possible causes of hanging: dbdeployer is using commands `ldd  mysql_executable` and `ldconfig -p` to find missing libraries. Please try these commands manually and report if they seem normal.

**Comment by geertjanvdk** [comment] 2019-10-26 09:19
I have just installed a server with Ubuntu (my colleague was using a laptop), and I could see that it takes quite long (more than 3 minutes, endless to me) to create a single instance. Without output of what is going on, users tend to hit Ctrl+C after a minute, wondering what is going on. Especially that the macOS users using dbdeployer have it like instant.

```
$ time ./dbdeployer deploy single 8.0.18 --port 3307 --sandbox-directory foo
Database installed in $HOME/sandboxes/foo
run 'dbdeployer usage single' for basic instructions'
....... sandbox server started

real	2m22.959s
user	0m4.089s
sys	0m1.530s
```

Similar with DBDeployer 1.39.

Takes about 3 seconds on Mac.

Would be great to have a note when this library checking is on going, saying that it might take a while. Maybe depending on the entries of LDD or so.

**Comment by datacharmer** [comment] 2019-10-26 10:09
I have seen a similar thing in my Ubuntu. Installation of 8.0.x takes a long time, while 5.7 is much faster.
On Docker container for Mac, installation is extremely fast, while on Ubuntu it is slower. I believe it may be a combination of kernel efficiency and storage type (I have 5 yo SSDs on Ubuntu).

The library checking is not responsible for the delay. Please try on your own Ubuntu box the commands:

* `time ldconfig -p`
* `time ldd ~/opt/mysql/8.0.18/bin/mysql`

Here's my attempt with two 8.0 and one 5.7 deployments with and without library check.
```
$ docker run -ti -v $HOME/opt:/root/opt  -v ~/go/bin/dbdeployer:/usr/bin/dbdeployer datacharmer/my-ubuntu bash
root@6d3f10968892:/# time dbdeployer deploy single 8.0 --skip-library-check
# 8.0 => 8.0.18
Creating directory /root/sandboxes
Database installed in $HOME/sandboxes/msb_8_0_18
run 'dbdeployer usage single' for basic instructions'
.. sandbox server started

real	0m42.370s
user	0m10.344s
sys	0m6.738s

root@6d3f10968892:/# time dbdeployer deploy single 8.0.17
Database installed in $HOME/sandboxes/msb_8_0_17
run 'dbdeployer usage single' for basic instructions'
.. sandbox server started

real	0m41.597s
user	0m9.384s
sys	0m6.059s

root@6d3f10968892:/# time dbdeployer deploy single 5.7
# 5.7 => 5.7.27
Database installed in $HOME/sandboxes/msb_5_7_27
run 'dbdeployer usage single' for basic instructions'
. sandbox server started

real	0m7.252s
user	0m1.009s

```

**Comment by geertjanvdk** [comment] 2019-10-26 15:06
Did the Docker thing, and be hold, sweetly fast :)

First of all, the library checking is really useful:

```
root@d6d3119f60b3:~# time dbdeployer deploy single 8.0.18 --port 3301 --sandbox-home foo
error while filling the sandbox definition: missing libraries will prevent MySQL from deploying correctly 

server (/root/opt/mysql/8.0.18/bin/mysqld): [	libaio.so.1 => not found 	libnuma.so.1 => not found]
global: [libaio libnuma]
.
Use --skip-library-check to skip this check

real	0m0.249s
```

This indeed helps.

When fixing the libraries, I got times which are more inline with what we have on macOS (I am only using 8.0.18 btw):

```
root@d6d3119f60b3:~# time dbdeployer deploy single 8.0.18 --port 3301 --sandbox-home foo
Creating directory /root/foo
Database installed in $HOME/foo/msb_8_0_18
run 'dbdeployer usage single' for basic instructions'
.. sandbox server started

real	0m7.627s
```

The docker image has the same stuff my physically server has. Server has a raid with spinning disks; at home I am using SSDs (Samsung SSD 850 EVO 1TB).

So, Giuseppe, we are at "it's a hardware problem"? :) but 7 seconds compared with 45s or > 2minutes minutes is bit off.

**Comment by datacharmer** [comment] 2019-10-26 17:24
Using the servers at my disposal I see that the experience is bearable. I have seen the slowness in 8.0.x since the early releases, and the reason is the ~5,000 transactions used to fill the GIS internal tables. If you enable the general log during initialization you will see it. 
For some strange reason, this set of transactions is extremely fast on Mac, reasonably fast on some rack servers, and deadly slow on some home servers.

I am open for suggestions if you know how the deployment could be improved. From my standpoint, it's an upstream problem.

**Comment by datacharmer** [comment] 2019-10-26 17:41
P.S. Please get on touch in [slack](https://mysqlcommunity.slack.com) if you want to look more deeply at the issue.

**Comment by morgo** [comment] 2019-10-26 22:38
> I have seen the slowness in 8.0.x since the early releases, and the reason is the ~5,000 transactions used to fill the GIS internal tables. If you enable the general log during initialization you will see it.

I believe this was fixed when upgrade was moved inside the server (8.0.16). As far as I remember, it was a limitation of the old upgrade framework.

**Comment by datacharmer** [comment] 2019-10-27 05:04
>I believe this was fixed when upgrade was moved inside the server (8.0.16). As far as I remember, it was a limitation of the old upgrade framework.

Yes, it was improved, but still the initialization of 8.0.x is way slower than 5.7.

**Comment by datacharmer** [comment] 2019-11-02 10:13
Since I don't see concrete action to take on this issue, I close it. Feel free to reopen if there are new facts to consider.

**Closed by datacharmer** 2019-11-02 10:13 UTC
