### ISSUE TITLE
Suggestion: my.sandbox.cnf to include report_port by default

### ISSUE THREAD

**Issue by shlomi-noach** [datacharmer/dbdeployer#7] opened 2018-04-12 08:29 UTC
When setting up a replication environment (`dbdeployer deploy replication`), and since everything is obviously installed on the same box, it makes sense that `dbdeployer` should add `report_port=<same-as-port>` automatically. There is no harm in doing so, and I find that this is a manual step I'm always taking after installing a sandbox setup.

`report_host` is a bit different, and I think it makes sense that I would include `--my-cnf-options report_host=127.0.0.1` if need be.

**Comment by datacharmer** [comment] 2018-04-13 03:45
MySQL-Sandbox sets both ``report-host`` and ``report-port``. The reason for setting ``report-host`` is that in old versions ``SHOW SLAVE HOSTS`` would report nothing unless ``report-host`` was set.
The output is:

    master [localhost] {msandbox} ((none)) > show slave hosts;
    +-----------+----------+-------+-----------+--------------------------------------+
    | Server_id | Host     | Port  | Master_id | Slave_UUID                           |
    +-----------+----------+-------+-----------+--------------------------------------+
    |       101 | SBslave1 | 20997 |         1 | 00020997-2222-2222-2222-222222222222 |
    |       102 | SBslave2 | 20998 |         1 | 00020998-3333-3333-3333-333333333333 |
    +-----------+----------+-------+-----------+--------------------------------------+

Each slave was adding ``--report-host=SBslave#`` to the configuration file. In other topologies, it was ``--report-host=node#``.

Since dbdeployer wants to reproduce the basic functioning of MySQL-Sandbox, this is a bug, which will be fixed soon.

Would you have any problems if I reintroduce the behavior of ``--report-host`` of showing a human readable value?

**Comment by shlomi-noach** [comment] 2018-04-13 10:09
I have no problem with auto-introducing `report-host` and can at worst override the value.

**Comment by datacharmer** [comment] 2018-04-14 18:45
This issue was resolved in [version 1.2.0](https://github.com/datacharmer/dbdeployer/releases/tag/1.2.0). By default, dbdeployer adds ``report-host`` and ``report-port`` to my.sandbox.cnf. Both options can be skipped using ``--skip-report-port`` and ``--skip-report-host``.

**Closed by datacharmer** 2018-04-14 18:45 UTC
Labels: bug
